### ISSUE TITLE
crbug/1173575

### ISSUE THREAD

**Issue by otobot1** [factoriolab/factoriolab.github.io#2] opened 2021-07-24 08:55 UTC
hi all of a sudden im getting this error in my chrome console whenever i try to load factoriolab.github.io "crbug/1173575, non-JS module files deprecated."

**Comment by dcbroad3** [comment] 2021-07-24 13:15
Just to clarify, is this preventing the calculator from loading, or just an error you noticed in the console?

**Comment by otobot1** [comment] 2021-07-24 14:39
Ah sorry, I was tired when I wrote that. Yes. It is preventing https://factoriolab.github.io/ from loading for me entirely. I'm getting "ERR_CONNECTION_RESET"

**Comment by dcbroad3** [comment] 2021-07-24 14:49
Can you try opening the site in a private browsing tab, or try disabling browser plugins? I'm not able to reproduce this error, at least on mobile. This is the only report I've seen of this error so for now my guess is it is a problem with your browser.

**Comment by otobot1** [comment] 2021-07-24 14:55
I tried incognito and firefox and neither worked. Firefox gave me this error. 

Secure Connection Failed

An error occurred during a connection to factoriolab.github.io. PR_CONNECT_RESET_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.



It does work on my android phone though. Over wifi.

**Comment by otobot1** [comment] 2021-07-24 14:58
I just tried closing chrome and reopening it before loading the page again. This time my AVG antivirus popped up and said it saved me from "URL phishing". I disabled AVG and the page loaded just fine.

**Comment by dcbroad3** [comment] 2021-07-24 15:18
Ah, that's interesting. I received a report that avast is throwing that warning again also, I just had both of them remove their warnings for this site last month and now they're back again. I'm guessing maybe that is the root cause then? I'll submit new requests to remove that warning.

**Comment by dcbroad3** [comment] 2021-07-24 15:21
By the way the main repository for this website is at https://github.com/factoriolab/factorio-lab, this repository just hosts the built output of the project. That's why there are no issues here.

**Comment by dcbroad3** [comment] 2021-07-26 13:56
Closing this as a duplicate of https://github.com/factoriolab/factorio-lab/issues/555.

**Closed by dcbroad3** 2021-07-26 13:56 UTC
